repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint -sn
                      --disable=all
                      --enable=missing-docstring,empty-docstring,parameter_documentation
                      --load-plugins=pylint.extensions.docparams
                      --accept-no-param-doc=false
                      --accept-no-raise-doc=false
                      --accept-no-result-doc=false
                      --accept-no-yields-doc=false
                      --docstring-min-length=10
                      --default-docstring-type=numpy
        language: system
        exclude: check_commit_template.py
        types: [python]
        
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [--explicit-package-bases, --ignore-missing-imports]